remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [CvetelinS toimenov QA Blog]
description: [Welcome to my QA Blog! Here, I’ll share insights, tutorials, and case studies related to Quality Assurance, testing tools, and best practices.]
