title: Cvetelin Stoimenov QA Blog
description: As an aspiring Quality Assurance (QA) professional, I am excited to share my journey and showcase the projects I’ve developed. This GitHub repository reflects my dedication to learning and applying QA principles through practical examples.
theme: jekyll-theme-cayman
collections:
  posts:
    output: true
